# Site settings
title: Muzzle Text Filtering
description: A comprehensive text filtering library for Node.js with flexible banned words sources
url: "https://ovendjs.github.io/Muzzle" # the base hostname & protocol for your site
baseurl: "/Muzzle" # the subpath of your site, e.g. /blog
author: Muzzle Contributors
license: MIT License
github_url: https://github.com/ovendjs/Muzzle
version: 1.1.0

# Build settings
markdown: kramdown
highlighter: rouge
theme: null # Using custom theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - getting-started.md
  - api-reference.md
  - configuration.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs-refactor-plan.md

# Collections
collections:
  api:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /examples/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "page"
  - scope:
      path: "index.md"
    values:
      layout: "home"
